version: '3.8'

services:
  postgres:
    container_name: nest-postgres
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: nest-postgres
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
  
  cache:
    container_name: nest-redis
    image: redis
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data
